export const CIRCLE_PROPS = [
  'circle-radius',
  'circle-radius-transition',
  'circle-color',
  'circle-color-transition',
  'circle-blur',
  'circle-blur-transition',
  'circle-opacity',
  'circle-opacity-transition',
  'circle-translate',
  'circle-translate-transition',
  'circle-translate-anchor',
  'circle-pitch-scale',
  'circle-pitch-alignment',
  'circle-stroke-width',
  'circle-stroke-width-transition',
  'circle-stroke-color',
  'circle-stroke-color-transition',
  'circle-stroke-opacity',
  'circle-stroke-opacity-transition',
] as const;

export const LINE_PROPS = [
  'line-opacity',
  'line-opacity-transition',
  'line-color',
  'line-color-transition',
  'line-translate',
  'line-translate-transition',
  'line-translate-anchor',
  'line-width',
  'line-width-transition',
  'line-gap-width',
  'line-gap-width-transition',
  'line-offset',
  'line-offset-transition',
  'line-blur',
  'line-blur-transition',
  'line-dasharray',
  'line-dasharray-transition',
  'line-pattern',
  'line-pattern-transition',
  'line-gradient',
] as const;

export const FILL_PROPS = [
  'fill-antialias',
  'fill-opacity',
  'fill-opacity-transition',
  'fill-color',
  'fill-color-transition',
  'fill-outline-color',
  'fill-outline-color-transition',
  'fill-translate',
  'fill-translate-transition',
  'fill-translate-anchor',
  'fill-pattern',
  'fill-pattern-transition',
] as const;

export const OUTLINED_FILL_PROPS = [
  'fill-antialias',
  'fill-opacity',
  'fill-opacity-transition',
  'fill-color',
  'fill-color-transition',
  'fill-translate',
  'fill-translate-transition',
  'fill-translate-anchor',
  'fill-pattern',
  'fill-pattern-transition',
  'fill-outline-opacity',
  'fill-outline-opacity-transition',
  'fill-outline-color',
  'fill-outline-color-transition',
  'fill-outline-translate',
  'fill-outline-translate-transition',
  'fill-outline-translate-anchor',
  'fill-outline-width',
  'fill-outline-width-transition',
  'fill-outline-gap-width',
  'fill-outline-gap-width-transition',
  'fill-outline-offset',
  'fill-outline-offset-transition',
  'fill-outline-blur',
  'fill-outline-blur-transition',
  'fill-outline-dasharray',
  'fill-outline-dasharray-transition',
  'fill-outline-pattern',
  'fill-outline-pattern-transition',
  'fill-outline-gradient',
] as const;
